include:
  - template: Auto-DevOps.gitlab-ci.yml
test:
  variables:
    MARIADB_VERSION: 10.2.41
    MARIADB_DATABASE: test
    MARIADB_USER: user
    MARIADB_PASSWORD: testing-password
    MARIADB_RANDOM_ROOT_PASSWORD: yes random
  services:
    - "mariadb:${MARIADB_VERSION}"
  stage: test
  image: gliderlabs/herokuish:latest
  needs: []
  script:
    - |
      if [ -z ${KUBERNETES_PORT+x} ]; then
        DB_HOST=mariadb
      else
        DB_HOST=127.0.0.1
      fi
    - export DATABASE_URL="mysql://${MARIADB_USER}:${MARIADB_PASSWORD}@${DB_HOST}:3306/${MARIADB_DATABASE}"
    - cp -R . /tmp/app
#    - echo "debug wait 300s"
#    - sleep 300
    - /bin/herokuish buildpack test
  rules:
    - if: '$TEST_DISABLED'
      when: never
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH'
